#!/usr/bin/env python3
"""One-command installer for the PythonAnywhere auto-deploy hook.

Run this in a Bash console on PythonAnywhere, inside your checkout:

    cd ~/HDC-MAIN
    python3 ops/pythonanywhere/install_deploy_hook.py

It does the three things that used to need hand-editing:

  1. creates ``deploy_secret.txt`` (a random shared key, gitignored, 0600)
  2. writes ``/var/www/<you>_pythonanywhere_com_wsgi.py`` from
     ``wsgi_dispatch_snippet.py`` -- backing up whatever was there and
     carrying over any ``os.environ`` / virtualenv lines it contained
  3. prints the exact values for the GitHub webhook form, including your
     real Payload URL and the secret to paste

Then click the green **Reload** button in the Web tab once.  Every push to
``main`` after that deploys itself.

Nothing here needs your username or paths typed in: they are detected.  If
detection guesses wrong, override with ``--username``, ``--repo`` or
``--wsgi-file``.

Other modes:
    --check          diagnose only, change nothing (paste this back for help)
    --dry-run        show exactly what would be written, change nothing
    --force          rewrite the WSGI file even if it is already installed
    --print-secret   print just the secret line
    --restore        put the most recent WSGI backup back
"""

import argparse
import glob
import os
import re
import secrets as pysecrets
import subprocess
import sys
import time

REPO_DIR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
if REPO_DIR not in sys.path:
    sys.path.insert(0, REPO_DIR)

import deploy_hook  # noqa: E402  (stdlib-only; safe to import anywhere)

BEGIN = "# >>> HDC deploy hook config (generated by install_deploy_hook.py) >>>"
END = "# <<< HDC deploy hook config <<<"
MARKER = "HDC deploy hook dispatch"
PRESERVE_HINTS = ("activate_this", "virtualenv", "sys.executable", "site-packages")
# Only real environment assignments are carried over -- anything else in the
# old file belonged to the old app, not to the app's configuration.
ENV_ASSIGNMENT = re.compile(
    r"^os\.environ\s*(\[[^\]]+\]\s*=|\.setdefault\s*\(|\.setenv|\.putenv)"
)


# --------------------------------------------------------------------------
# detection
# --------------------------------------------------------------------------
def detect(args):
    """Resolve repo / username / wsgi path from flags, env, then the machine."""
    repo = os.path.abspath(os.path.expanduser(args.repo or deploy_hook.detect_repo_dir()))
    username = (args.username or "").strip() or deploy_hook.detect_username()
    var_www = os.path.expanduser(args.var_www) if args.var_www else deploy_hook.VAR_WWW
    if args.wsgi_file:
        wsgi = os.path.abspath(os.path.expanduser(args.wsgi_file))
    else:
        wsgi = deploy_hook.detect_wsgi_file(var_www)
        # A WSGI filename is the most reliable source of the username on PA.
        if not username:
            username = deploy_hook.username_from_wsgi_name(wsgi)
        if username and not os.path.exists(wsgi):
            # Nothing found yet: fall back to the conventional name for the
            # username we did resolve (a flag beats whatever USER says).
            wsgi = os.path.join(var_www, f"{username}_pythonanywhere_com_wsgi.py")
    domain = (args.domain or "").strip() or (
        f"{username}.pythonanywhere.com" if username else "<your-username>.pythonanywhere.com"
    )
    return {
        "repo": repo,
        "secret": os.path.join(repo, "deploy_secret.txt"),
        "username": username,
        "wsgi": wsgi,
        "domain": domain,
        "branch": (args.branch or "").strip() or deploy_hook.BRANCH,
        "payload_url": f"https://{domain}/deploy",
    }


def read_snippet(repo):
    path = os.path.join(repo, "wsgi_dispatch_snippet.py")
    if not os.path.isfile(path):
        raise SystemExit(f"missing {path} -- are you running this inside the HDC-MAIN checkout?")
    with open(path, encoding="utf-8") as handle:
        return handle.read()


# Lines the header itself generates, so they are never "carried over" twice.
OWN_HEADER_LINES = ("import os", "import sys")
PIN_PREFIX = "HDC_REPO_DIR_DEFAULT"
# Any hand-written or older HDC_REPO_DIR assignment is replaced by the pin,
# never carried over -- a stale one would override the path we just detected.
REPO_DIR_LINE = re.compile(r"^os\.environ.*[\[\"\']HDC_REPO_DIR")


def preserved_lines(old_text):
    """Keep the previous WSGI file's env/virtualenv setup lines.

    Those are how the database path and secrets reach the app, so silently
    dropping them would break a working site.  Everything from the dispatch
    marker downwards is generated snippet code and is ignored; inside our own
    header block only the lines we generate are ignored, so lines carried over
    on an earlier run survive a re-install.
    """
    dropped_repo_dir_lines = []
    if not old_text:
        return []
    cut = old_text.find(MARKER)
    head = old_text if cut == -1 else old_text[:cut]
    kept = []
    for raw in head.splitlines():
        line = raw.rstrip()
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith((BEGIN, END)):
            continue
        if stripped in OWN_HEADER_LINES or stripped.startswith(PIN_PREFIX):
            continue
        if REPO_DIR_LINE.match(stripped):
            dropped_repo_dir_lines.append(line)
            continue
        if ENV_ASSIGNMENT.match(stripped) or any(h in stripped for h in PRESERVE_HINTS):
            kept.append(line)
    seen, out = set(), []   # de-duplicate, keep order
    for line in kept:
        if line not in seen:
            seen.add(line)
            out.append(line)
    preserved_lines.dropped_repo_dir_lines = dropped_repo_dir_lines
    return out


preserved_lines.dropped_repo_dir_lines = []


def build_wsgi_text(snippet_text, repo, old_text=""):
    """Header (pinned repo path + carried-over env lines) then the snippet."""
    preserved = preserved_lines(old_text)
    lines = [BEGIN, "import os"]
    if any("sys." in line or "activate_this" in line for line in preserved):
        lines.append("import sys")
    lines += preserved
    lines.append(f"{PIN_PREFIX} = {repo!r}")
    lines += [END, "", snippet_text.rstrip("\n"), ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# steps
# --------------------------------------------------------------------------
def ensure_secret(secret_file, dry_run=False):
    """Create deploy_secret.txt if needed. Returns (secret, created)."""
    if os.path.isfile(secret_file):
        with open(secret_file, encoding="utf-8") as handle:
            existing = handle.read().strip()
        if existing:
            return existing, False
    token = pysecrets.token_urlsafe(24)
    if dry_run:
        return token, True
    with open(secret_file, "w", encoding="utf-8") as handle:
        handle.write(token + "\n")
    try:
        os.chmod(secret_file, 0o600)
    except OSError:
        pass
    return token, True


def git(repo, *args):
    try:
        return subprocess.check_output(
            ["git"] + list(args), cwd=repo, stderr=subprocess.STDOUT
        ).decode(errors="replace").strip()
    except Exception as ex:
        return f"(git failed: {ex})"


def diagnose(cfg):
    """Facts worth printing, both for --check and after a successful install."""
    repo = cfg["repo"]
    out = []
    out.append(f"repo folder      : {repo}")
    out.append(f"repo looks right : {'yes' if os.path.isfile(os.path.join(repo, 'hdc', 'app.py')) else 'NO - hdc/app.py not found'}")
    out.append(f"python           : {sys.executable} ({sys.version.split()[0]})")
    out.append(f"git remote       : {git(repo, 'remote', 'get-url', 'origin')}")
    out.append(f"git branch       : {git(repo, 'rev-parse', '--abbrev-ref', 'HEAD')}")
    out.append(f"git HEAD         : {git(repo, 'rev-parse', '--short', 'HEAD')}")
    dirty = git(repo, "status", "--porcelain")
    out.append(
        "working tree     : "
        + ("clean" if not dirty or dirty.startswith("(git failed") else "DIRTY - a pull will fail until this is stashed:\n" + dirty)
    )
    out.append(f"secret file      : {cfg['secret']} "
               f"({'present' if os.path.isfile(cfg['secret']) else 'MISSING'})")
    out.append(f"wsgi file        : {cfg['wsgi']} ({'present' if os.path.isfile(cfg['wsgi']) else 'MISSING'})")
    if os.path.isfile(cfg["wsgi"]):
        with open(cfg["wsgi"], encoding="utf-8", errors="replace") as handle:
            current = handle.read()
        out.append(f"hook mounted     : {'yes' if MARKER in current else 'NO - still the old WSGI file'}")
    else:
        out.append("hook mounted     : no")
    out.append(f"deploy log       : {os.path.join(repo, 'deploy.log')}")
    return out


def install(cfg, args):
    """Write the secret + WSGI file. Returns a list of report lines."""
    report = []
    secret, created = ensure_secret(cfg["secret"], dry_run=args.dry_run)
    report.append(
        (("would create " if args.dry_run else "created ") + cfg["secret"])
        if created
        else f"secret already exists: {cfg['secret']} (kept as-is)"
    )

    snippet_text = read_snippet(cfg["repo"])
    old_text = ""
    if os.path.isfile(cfg["wsgi"]):
        with open(cfg["wsgi"], encoding="utf-8", errors="replace") as handle:
            old_text = handle.read()

    already = MARKER in old_text
    new_text = build_wsgi_text(snippet_text, cfg["repo"], old_text)

    if already and new_text == old_text and not args.force:
        report.append(f"WSGI file already installed and unchanged: {cfg['wsgi']}")
        return report, secret

    if already and not args.force:
        report.append(
            f"WSGI file already installed; rewriting it with the current snippet ({cfg['wsgi']})"
        )

    if not args.dry_run:
        if old_text:
            backup = f"{cfg['wsgi']}.bak-{time.strftime('%Y%m%d-%H%M%S')}"
            with open(backup, "w", encoding="utf-8") as handle:
                handle.write(old_text)
            report.append(f"backed up old WSGI file -> {backup}")
            kept = preserved_lines(old_text)
            report.append(
                "carried over from the old file: "
                + (", ".join(line.strip() for line in kept) if kept else "nothing (no env/virtualenv lines found)")
            )
            for line in preserved_lines.dropped_repo_dir_lines:
                report.append(f"replaced stale repo path line: {line.strip()}")
        os.makedirs(os.path.dirname(cfg["wsgi"]), exist_ok=True)
        with open(cfg["wsgi"], "w", encoding="utf-8") as handle:
            handle.write(new_text)
        report.append(f"wrote {cfg['wsgi']} ({len(new_text.splitlines())} lines)")
        try:
            compile(new_text, cfg["wsgi"], "exec")
            report.append("syntax check: OK")
        except SyntaxError as ex:
            report.append(f"SYNTAX CHECK FAILED (restore the backup): {ex}")
    else:
        report.append(f"would write {cfg['wsgi']}:\n" + "-" * 60 + "\n" + new_text + "-" * 60)
    return report, secret


def restore(cfg):
    backups = sorted(glob.glob(cfg["wsgi"] + ".bak-*"))
    if not backups:
        raise SystemExit(f"no backups found matching {cfg['wsgi']}.bak-*")
    latest = backups[-1]
    with open(latest, encoding="utf-8") as handle:
        text = handle.read()
    with open(cfg["wsgi"], "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"restored {latest} -> {cfg['wsgi']}\nNow click Reload in the Web tab.")


def summary(cfg, secret):
    return [
        "",
        "=" * 68,
        "NEXT: Web tab -> big green Reload button (once).",
        "",
        "Then open this in your browser -- it should print the config:",
        f"    {cfg['payload_url']}",
        "",
        "GitHub -> Settings -> Webhooks -> Add webhook (or edit the old one):",
        f"    Payload URL  : {cfg['payload_url']}",
        "    Content type : application/json",
        f"    Secret       : {secret}",
        "    SSL          : Enable SSL verification",
        "    Events       : Just the push event",
        "    Active       : ticked",
        "",
        "Test it from your computer:",
        '    git commit --allow-empty -m "test deploy hook" && git push origin '
        + cfg["branch"],
        f"then reopen {cfg['payload_url']} and look for: OK deployed <hash>",
        "=" * 68,
    ]


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", help="path to the HDC-MAIN checkout (auto-detected)")
    parser.add_argument("--username", help="PythonAnywhere username (auto-detected)")
    parser.add_argument("--wsgi-file", help="WSGI file to write (auto-detected)")
    parser.add_argument("--var-www", help="folder to search for the WSGI file (default /var/www)")
    parser.add_argument("--domain", help="site domain (default <username>.pythonanywhere.com)")
    parser.add_argument("--branch", help="branch that triggers a deploy (default main)")
    parser.add_argument("--check", action="store_true", help="diagnose only, write nothing")
    parser.add_argument("--dry-run", action="store_true", help="show what would be written")
    parser.add_argument("--force", action="store_true", help="rewrite even if already installed")
    parser.add_argument("--print-secret", action="store_true", help="print only the secret")
    parser.add_argument("--restore", action="store_true", help="restore the newest WSGI backup")
    args = parser.parse_args(argv)

    cfg = detect(args)

    if args.print_secret:
        secret, _ = ensure_secret(cfg["secret"], dry_run=True)
        print(secret)
        return 0
    if args.restore:
        restore(cfg)
        return 0

    print("\n".join(diagnose(cfg)))

    if args.check:
        print("\n--check: nothing was written.")
        return 0

    report, secret = install(cfg, args)
    print()
    for line in report:
        print("  " + line)
    if args.dry_run:
        print("\n--dry-run: nothing was written.")
        return 0
    print("\n".join(summary(cfg, secret)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
